### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by alindeman** [rspec/rspec-dev#43]
- [ ] Draft blog post (?)
- [x] Checkout the latest code and get bundles current
  - `rake change_branch[master]`
- [x] Update changelogs in all repos
  - Add version number and URL to each README
  - `rake 'git:commit[Updates changelog for vX.Y.Z [ci skip]]'`
  - `rake git:push`
- [x] Update version number in all repos
  - `rake 'gem:write_version[X.Y.Z]'`
  - `rake 'git:commit[Releases X.Y.Z]'`
- [ ] Release gems
  - `rake gem:release`
- [ ] Branch `X-Y-maintenance` in all repos (if first X.Y release)
  - `rake 'git:checkout[-b X-Y-maintenance]'`
  - Update `maintenance-branch` file in each
  - `rake 'git:commit[Updates maintenance-branch file [ci skip]]'`
  - `rake "run[git push origin X-Y-maintenance -u]"`
- [ ] Update docs
  - `rake 'relish[X.Y]'` (exclude .Z). To run this you need relish push access.
  - `rake 'update_docs[X.Y, X-Y-maintenance]'`. To run this you need `rspec.github.io` in your `repos` directory, with the `source` branch checked out.
- [ ] Update version to `X.Y+1.pre` in master.
  - `rake 'git:checkout[master]'`
  - `rake 'gem:write_version[X.Y+1.pre]'`
  - `rake 'git:commit[Bump version...]'`
  - `rake git:push`
- [ ] Publish blog post
  - Use `rake version_stats[vX.(Y - 1).0...vX.Y]` to get version stats for post. 
  - Put changelog release notes into blog post.
  - Run `middleman deploy` from `rspec.github.io` checkout to deploy to staging and `TARGET=prod middleman deploy` for a prod deploy.
- [ ] Tweet from @rspec account
- [ ] Notify mailing list (link to the blog post)
